name: Deploy to CapRover

env:
  CONTEXT_DIR: "./"
  IMAGE_NAME: ${{ github.repository }}
  DOCKERFILE: Dockerfile
  CAPROVER_APP: naelp22

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set Repository and Image Name
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          IMAGE_NAME=$DOCKER_USERNAME/$REPO_NAME
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "FULL_IMAGE_NAME=$REPO_NAME:$(date +%s)" >> $GITHUB_ENV
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - uses: actions/checkout@v1
      - run: |
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "FULL_IMAGE_NAME=$IMAGE_NAME:$(date +%s)" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Release to DockerHub
        shell: bash
        run: |
          docker build \
            --build-arg EMAIL_HOST=${{ secrets.EMAIL_HOST }} \
            --build-arg EMAIL_PORT=${{ secrets.EMAIL_PORT }} \
            --build-arg EMAIL_USER=${{ secrets.EMAIL_USER }} \
            --build-arg EMAIL_PASS=${{ secrets.EMAIL_PASS }} \
           --build-arg EMAIL_TO=${{ secrets.EMAIL_TO }} \
           -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest .

           docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPROVER_HOST }}
          app: ${{ env.CAPROVER_APP }}
          token: "${{ secrets.CAPROVER_APP_TOKEN }}"
          image: "${{ env.FULL_IMAGE_NAME }}"
